[build]
base = "frontend/react-app"
publish = "../site"
command = """
# Build Web App
npm run build && rm -rf ../site && mkdir ../site/app && cp -r dist/* ../site/app/

# Landing page
cd ../../frontend/quickclips-landing
npm run build && mkdir ../site && cp -r dist/* ../site
""""
functions = "netlify/functions" 



[[redirects]]
from = "/app/*"
to = "/app/index.html"
status = 200
force = false
